.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. gdrcoin_qt test_gdrcoin_qt
clean: FORCE
	$(MAKE) -C .. gdrcoin_qt_clean test_gdrcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_gdrcoin_qt_check
gdrcoin-qt gdrcoin-qt.exe: FORCE
	 $(MAKE) -C .. gdrcoin_qt
